# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UmbrellaTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UmbrellaTest
  pod 'Models', :path => 'Models'
  pod 'Networking', :path => 'Networking'

end
