excluded:
  - .swiftpm/
  - .vscode/
  - "**/.build/*"
  - .build/
  - TestAssets/
  - PIF/.build/
  - '**/Package.swift'
  - Package.swift
  - PIF/Sources/pif-parser/pif-parser.swift

disabled_rules:
  - todo
  - nesting

line_length:
  warning: 200
  ignores_comments: true

missing_docs:
  warning:
    - private
    - public

opt_in_rules:
  - missing_docs
