excluded:
  - .build/
  - .swiftpm/
  - .vscode/
  # https://github.com/realm/SwiftLint/issues/2329 doesn't support recursive globs yet
  - GenIRLogging/.build/
  - TestAssets/

disabled_rules:
  - todo
  - nesting

line_length:
  warning: 200
  ignores_comments: true
