excluded:
  - .swiftpm/
  - .vscode/
  - "**/.build/*"
  - .build/
  - TestAssets/
  - PIF/.build/

disabled_rules:
  - todo
  - nesting

line_length:
  warning: 200
  ignores_comments: true

missing_docs:
  warning:
  - private
  - open
  - fileprivate
  - public
  - internal

opt_in_rules:
  - missing_docs
