name: Build

on:
  pull_request:
    paths:
      - '**.swift'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🔨 Build
        run: |
          swift build
          swift test
